"""
Free stock news search provider using DuckDuckGo Search (DDGS) and yfinance news.
100% free, no API key required, with strict 4-second timeouts to prevent freezing.

Also supports reusing Google Search-grounded news from the daily news_summary.json
(generated by news_summary.py) to avoid redundant API calls.
"""

import os
import time
import yfinance as yf
from datetime import datetime, timezone


def _bare_ticker(ticker):
    if ticker.endswith(".NS") or ticker.endswith(".BO"):
        return ticker.rsplit(".", 1)[0]
    return ticker


def _try_google_summary_news(ticker, market):
    """
    Try to extract ticker-specific news from today's news_summary.json,
    which was fetched via Google Search grounding (the highest quality source).
    Returns (text, "🔍 Google Search") if found and fresh, else (None, None).
    """
    try:
        SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
        import json
        summary_path = os.path.join(SCRIPT_DIR, "news_summary.json")
        if not os.path.exists(summary_path):
            return None, None
        with open(summary_path) as f:
            summary_data = json.load(f)

        from datetime import timedelta
        # Check freshness using generated_at timestamp (allow up to 24 hours old)
        gen_at_str = summary_data.get("generated_at")
        if not gen_at_str:
            return None, None
            
        try:
            gen_time = datetime.fromisoformat(gen_at_str)
            if datetime.now(timezone.utc) - gen_time > timedelta(hours=48):
                return None, None  # Stale data — don't reuse
        except Exception:
            return None, None

        market_summary = summary_data.get("markets", {}).get(market, {}).get("summary", "")
        if not market_summary:
            return None, None

        bare = _bare_ticker(ticker)
        relevant_lines = [
            line.strip()
            for line in market_summary.split("\n")
            if bare.lower() in line.lower() and line.strip()
        ]
        if relevant_lines:
            return "\n".join(relevant_lines), "🔍 Google Search (News Summary)"
    except Exception:
        pass
    return None, None


def get_stock_news(ticker, market=None, max_results=4, timeout_sec=4):
    """
    Fetches recent news for a ticker using (in priority order):
      1. Google Search grounding from news_summary.json (if today's data exists)
      2. DuckDuckGo News Search
      3. Yahoo Finance (yfinance) backup

    Returns:
        (text: str, source: str) — formatted news string and the source label used.
    """
    google_text, google_source = None, None
    if market:
        google_text, google_source = _try_google_summary_news(ticker, market)

    bare = _bare_ticker(ticker)
    news_items = []
    sources_used = []

    if google_text:
        sources_used.append(google_source)

    # Priority 2: DuckDuckGo News Search
    try:
        from duckduckgo_search import DDGS
        query = f"{bare} stock news"
        with DDGS(timeout=timeout_sec) as ddgs:
            results = list(ddgs.news(query, max_results=max_results))
            for r in results:
                title = r.get("title")
                source = r.get("source")
                date_str = r.get("date") or ""
                if title:
                    news_items.append({
                        "title": title,
                        "source": source or "Web",
                        "date": date_str[:10] if len(date_str) >= 10 else "Recent",
                    })
        if news_items:
            sources_used.append("🦆 DuckDuckGo")
    except Exception as e:
        print(f"  [ddgs news warning] {ticker}: {e}")

    # Priority 3: Yahoo Finance backup
    if len(news_items) < max_results:
        try:
            yf_news = yf.Ticker(ticker).news
            added_from_yf = 0
            if yf_news:
                for item in yf_news[:max_results]:
                    title = item.get("title")
                    publisher = item.get("publisher")
                    pub_time = item.get("providerPublishTime")
                    date_str = time.strftime("%Y-%m-%d", time.gmtime(pub_time)) if pub_time else "Recent"
                    if title and not any(n["title"] == title for n in news_items):
                        news_items.append({
                            "title": title,
                            "source": publisher or "Yahoo Finance",
                            "date": date_str,
                        })
                        added_from_yf += 1
            if added_from_yf > 0:
                sources_used.append("📰 Yahoo Finance")
        except Exception as e:
            print(f"  [yf news warning] {ticker}: {e}")

    if not news_items and not google_text:
        return "No recent major news or announcements found in the last 48 hours.", "⚪ No Source"

    formatted = []
    if google_text:
        formatted.append(google_text)

    if news_items:
        for item in news_items[:max_results]:
            formatted.append(f"- [{item['date']}] {item['title']} (Source: {item['source']})")

    source_label = " + ".join(sources_used) if sources_used else "⚪ Unknown"
    return "\n".join(formatted), source_label


if __name__ == "__main__":
    print("Testing get_stock_news for LAURUSLABS.NS...")
    text, source = get_stock_news("LAURUSLABS.NS", market="INDIA")
    print(f"Source: {source}")
    print(text)
